version: "3"
volumes:
  postgres:
  rails_cache:
  bundle:
  node_modules:
  packs:
services:
  box:
    image: busybox
    volumes:
      - /box
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  web: &web
    build:
      context: .
    command: ./scripts/start
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - postgres:/var/lib/postgres/data
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      EDITOR: nano
      SUPER_ADMINS: "cmwoodall@yahoo.com;"
