version: '3'
volumes:
  box:
  app:
  db:
  rails_cache:
  bundle:
  node_modules:
  packs:
services:
  box:
    image: busybox
    volumes:
      - /box
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
  web: &web
    build:
      context: .
    command: ./scripts/start
    volumes:
      - .:/app
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - box:/box
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      EDITOR: nano
  webpacker:
    <<: *web
    command: bundle exec ./bin/webpack-dev-server        
    ports:
      - 3035:3035
    environment:
      NODE_ENV: development
      WEBPACK_DEV_SERVER_HOST: 0.0.0.0
    depends_on:
      - postgres