require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::PlayingSurfacesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlayingSurface. As you add validations to PlayingSurface, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::PlayingSurfacesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all playing_surfaces as @playing_surfaces" do
      playing_surface = PlayingSurface.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:playing_surfaces)).to eq([playing_surface])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_playing_surface as @admin_playing_surface" do
      playing_surface = PlayingSurface.create! valid_attributes
      get :show, {:id => playing_surface.to_param}, valid_session
      expect(assigns(:admin_playing_surface)).to eq(playing_surface)
    end
  end

  describe "GET new" do
    it "assigns a new admin_playing_surface as @admin_playing_surface" do
      get :new, {}, valid_session
      expect(assigns(:admin_playing_surface)).to be_a_new(PlayingSurface)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_playing_surface as @admin_playing_surface" do
      playing_surface = PlayingSurface.create! valid_attributes
      get :edit, {:id => playing_surface.to_param}, valid_session
      expect(assigns(:admin_playing_surface)).to eq(playing_surface)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayingSurface" do
        expect {
          post :create, {:admin_playing_surface => valid_attributes}, valid_session
        }.to change(PlayingSurface, :count).by(1)
      end

      it "assigns a newly created admin_playing_surface as @admin_playing_surface" do
        post :create, {:admin_playing_surface => valid_attributes}, valid_session
        expect(assigns(:admin_playing_surface)).to be_a(PlayingSurface)
        expect(assigns(:admin_playing_surface)).to be_persisted
      end

      it "redirects to the created admin_playing_surface" do
        post :create, {:admin_playing_surface => valid_attributes}, valid_session
        expect(response).to redirect_to(PlayingSurface.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_playing_surface as @admin_playing_surface" do
        post :create, {:admin_playing_surface => invalid_attributes}, valid_session
        expect(assigns(:admin_playing_surface)).to be_a_new(PlayingSurface)
      end

      it "re-renders the 'new' template" do
        post :create, {:admin_playing_surface => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_playing_surface" do
        playing_surface = PlayingSurface.create! valid_attributes
        put :update, {:id => playing_surface.to_param, :admin_playing_surface => new_attributes}, valid_session
        playing_surface.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested admin_playing_surface as @admin_playing_surface" do
        playing_surface = PlayingSurface.create! valid_attributes
        put :update, {:id => playing_surface.to_param, :admin_playing_surface => valid_attributes}, valid_session
        expect(assigns(:admin_playing_surface)).to eq(playing_surface)
      end

      it "redirects to the admin_playing_surface" do
        playing_surface = PlayingSurface.create! valid_attributes
        put :update, {:id => playing_surface.to_param, :admin_playing_surface => valid_attributes}, valid_session
        expect(response).to redirect_to(playing_surface)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_playing_surface as @admin_playing_surface" do
        playing_surface = PlayingSurface.create! valid_attributes
        put :update, {:id => playing_surface.to_param, :admin_playing_surface => invalid_attributes}, valid_session
        expect(assigns(:admin_playing_surface)).to eq(playing_surface)
      end

      it "re-renders the 'edit' template" do
        playing_surface = PlayingSurface.create! valid_attributes
        put :update, {:id => playing_surface.to_param, :admin_playing_surface => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_playing_surface" do
      playing_surface = PlayingSurface.create! valid_attributes
      expect {
        delete :destroy, {:id => playing_surface.to_param}, valid_session
      }.to change(PlayingSurface, :count).by(-1)
    end

    it "redirects to the playing_surfaces list" do
      playing_surface = PlayingSurface.create! valid_attributes
      delete :destroy, {:id => playing_surface.to_param}, valid_session
      expect(response).to redirect_to(playing_surfaces_url)
    end
  end

end
