# == Schema Information
#
# Table name: registrar_registrables
#
#  id                 :integer          not null, primary key
#  parent_id          :integer
#  parent_type        :string
#  title              :string(30)
#  description        :text
#  quantity_allowed   :integer
#  quantity_available :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  tenant_id          :integer
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Registrar::RegistrablesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Registrar::Registrable. As you add validations to Registrar::Registrable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Registrar::RegistrablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registrar_registrables as @registrar_registrables" do
      registrable = Registrar::Registrable.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:registrar_registrables)).to eq([registrable])
    end
  end

  describe "GET show" do
    it "assigns the requested registrar_registrable as @registrar_registrable" do
      registrable = Registrar::Registrable.create! valid_attributes
      get :show, {:id => registrable.to_param}, valid_session
      expect(assigns(:registrar_registrable)).to eq(registrable)
    end
  end

  describe "GET new" do
    it "assigns a new registrar_registrable as @registrar_registrable" do
      get :new, {}, valid_session
      expect(assigns(:registrar_registrable)).to be_a_new(Registrar::Registrable)
    end
  end

  describe "GET edit" do
    it "assigns the requested registrar_registrable as @registrar_registrable" do
      registrable = Registrar::Registrable.create! valid_attributes
      get :edit, {:id => registrable.to_param}, valid_session
      expect(assigns(:registrar_registrable)).to eq(registrable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registrar::Registrable" do
        expect {
          post :create, {:registrar_registrable => valid_attributes}, valid_session
        }.to change(Registrar::Registrable, :count).by(1)
      end

      it "assigns a newly created registrar_registrable as @registrar_registrable" do
        post :create, {:registrar_registrable => valid_attributes}, valid_session
        expect(assigns(:registrar_registrable)).to be_a(Registrar::Registrable)
        expect(assigns(:registrar_registrable)).to be_persisted
      end

      it "redirects to the created registrar_registrable" do
        post :create, {:registrar_registrable => valid_attributes}, valid_session
        expect(response).to redirect_to(Registrar::Registrable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registrar_registrable as @registrar_registrable" do
        post :create, {:registrar_registrable => invalid_attributes}, valid_session
        expect(assigns(:registrar_registrable)).to be_a_new(Registrar::Registrable)
      end

      it "re-renders the 'new' template" do
        post :create, {:registrar_registrable => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested registrar_registrable" do
        registrable = Registrar::Registrable.create! valid_attributes
        put :update, {:id => registrable.to_param, :registrar_registrable => new_attributes}, valid_session
        registrable.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested registrar_registrable as @registrar_registrable" do
        registrable = Registrar::Registrable.create! valid_attributes
        put :update, {:id => registrable.to_param, :registrar_registrable => valid_attributes}, valid_session
        expect(assigns(:registrar_registrable)).to eq(registrable)
      end

      it "redirects to the registrar_registrable" do
        registrable = Registrar::Registrable.create! valid_attributes
        put :update, {:id => registrable.to_param, :registrar_registrable => valid_attributes}, valid_session
        expect(response).to redirect_to(registrable)
      end
    end

    describe "with invalid params" do
      it "assigns the registrar_registrable as @registrar_registrable" do
        registrable = Registrar::Registrable.create! valid_attributes
        put :update, {:id => registrable.to_param, :registrar_registrable => invalid_attributes}, valid_session
        expect(assigns(:registrar_registrable)).to eq(registrable)
      end

      it "re-renders the 'edit' template" do
        registrable = Registrar::Registrable.create! valid_attributes
        put :update, {:id => registrable.to_param, :registrar_registrable => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registrar_registrable" do
      registrable = Registrar::Registrable.create! valid_attributes
      expect {
        delete :destroy, {:id => registrable.to_param}, valid_session
      }.to change(Registrar::Registrable, :count).by(-1)
    end

    it "redirects to the registrar_registrables list" do
      registrable = Registrar::Registrable.create! valid_attributes
      delete :destroy, {:id => registrable.to_param}, valid_session
      expect(response).to redirect_to(registrar_registrables_url)
    end
  end

end
