require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Registrar::SessionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Registrar::Session. As you add validations to Registrar::Session, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Registrar::SessionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registrar_sessions as @registrar_sessions" do
      session = Registrar::Session.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:registrar_sessions)).to eq([session])
    end
  end

  describe "GET show" do
    it "assigns the requested registrar_session as @registrar_session" do
      session = Registrar::Session.create! valid_attributes
      get :show, {:id => session.to_param}, valid_session
      expect(assigns(:registrar_session)).to eq(session)
    end
  end

  describe "GET new" do
    it "assigns a new registrar_session as @registrar_session" do
      get :new, {}, valid_session
      expect(assigns(:registrar_session)).to be_a_new(Registrar::Session)
    end
  end

  describe "GET edit" do
    it "assigns the requested registrar_session as @registrar_session" do
      session = Registrar::Session.create! valid_attributes
      get :edit, {:id => session.to_param}, valid_session
      expect(assigns(:registrar_session)).to eq(session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registrar::Session" do
        expect {
          post :create, {:registrar_session => valid_attributes}, valid_session
        }.to change(Registrar::Session, :count).by(1)
      end

      it "assigns a newly created registrar_session as @registrar_session" do
        post :create, {:registrar_session => valid_attributes}, valid_session
        expect(assigns(:registrar_session)).to be_a(Registrar::Session)
        expect(assigns(:registrar_session)).to be_persisted
      end

      it "redirects to the created registrar_session" do
        post :create, {:registrar_session => valid_attributes}, valid_session
        expect(response).to redirect_to(Registrar::Session.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registrar_session as @registrar_session" do
        post :create, {:registrar_session => invalid_attributes}, valid_session
        expect(assigns(:registrar_session)).to be_a_new(Registrar::Session)
      end

      it "re-renders the 'new' template" do
        post :create, {:registrar_session => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested registrar_session" do
        session = Registrar::Session.create! valid_attributes
        put :update, {:id => session.to_param, :registrar_session => new_attributes}, valid_session
        session.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested registrar_session as @registrar_session" do
        session = Registrar::Session.create! valid_attributes
        put :update, {:id => session.to_param, :registrar_session => valid_attributes}, valid_session
        expect(assigns(:registrar_session)).to eq(session)
      end

      it "redirects to the registrar_session" do
        session = Registrar::Session.create! valid_attributes
        put :update, {:id => session.to_param, :registrar_session => valid_attributes}, valid_session
        expect(response).to redirect_to(session)
      end
    end

    describe "with invalid params" do
      it "assigns the registrar_session as @registrar_session" do
        session = Registrar::Session.create! valid_attributes
        put :update, {:id => session.to_param, :registrar_session => invalid_attributes}, valid_session
        expect(assigns(:registrar_session)).to eq(session)
      end

      it "re-renders the 'edit' template" do
        session = Registrar::Session.create! valid_attributes
        put :update, {:id => session.to_param, :registrar_session => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registrar_session" do
      session = Registrar::Session.create! valid_attributes
      expect {
        delete :destroy, {:id => session.to_param}, valid_session
      }.to change(Registrar::Session, :count).by(-1)
    end

    it "redirects to the registrar_sessions list" do
      session = Registrar::Session.create! valid_attributes
      delete :destroy, {:id => session.to_param}, valid_session
      expect(response).to redirect_to(registrar_sessions_url)
    end
  end

end
