
development:
  sessions:
    default:
      database: sportified_development
      hosts:
        - localhost
  options:
    use_utc: false
    use_activesupport_time_zone: true

test:
  sessions:
    default:
      database: sportified_test
      hosts:
        - localhost
  options:

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:


