defaults: &defaults
  host: localhost
  idendity_map_enabled: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: sportified_development

test:
  <<: *defaults
  database: sportified_test

# set these environment variables on your prod server
production:
  database: sportified
  idendity_map_enabled: true  
  uri: <%= ENV['MONGOHQ_URL'] %>
#  host: <%= ENV['MONGOID_HOST'] %>
#  port: <%= ENV['MONGOID_PORT'] %>
#  username: <%= ENV['MONGOID_USERNAME'] %>
#  password: <%= ENV['MONGOID_PASSWORD'] %>
#  database: <%= ENV['MONGOID_DATABASE'] %>
