
development:
  sessions:
    default:
      database: sportified_development
      hosts:
        - localhost
  options:
    identity_map_enabled: true

test:
  sessions:
    default:
      database: sportified_test
      hosts:
        - localhost
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    identity_map_enabled: true

