#!/bin/bash

# docker build --target build -t sportified:build --build-arg RAILS_MASTER_KEY=$(cat config/master.key) .
docker build --target release -t sportified:release --build-arg RAILS_MASTER_KEY=$(cat config/master.key) .