#!/bin/bash

if ! command -v foreman &> /dev/null
then
  echo "Installing foreman..."
  gem install foreman
fi

bundle check || bundle install

rm -f tmp/pids/server.pid

foreman start -f Procfile.dev